# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  # Add any additional Firebase services you are using

  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
