
import 'translation_key_manager.dart';

Map<String, String> ar =
{
  TranslationKeyManager.home : 'الشاشة الرئيسية',
  TranslationKeyManager.settings : 'الاعدادات',
  TranslationKeyManager.hello : 'مرحبا',
  TranslationKeyManager.school : 'مدرسة',
  TranslationKeyManager.schoolA : 'المدرسة',
  TranslationKeyManager.schools : 'المدارس',
  TranslationKeyManager.all : 'كل',

  TranslationKeyManager.profile : 'الحساب',
  TranslationKeyManager.pickup : 'استدعاء',
  TranslationKeyManager.pickupRequests : 'طلبات الاستدعاء',
  TranslationKeyManager.waiting : 'انتظار',
  TranslationKeyManager.accepted  : 'موافقة',
  TranslationKeyManager.rejected  : 'رفض',
  TranslationKeyManager.noData  : 'لا يوجد بيانات',
  TranslationKeyManager.parents  : 'اولياء الامور',
  TranslationKeyManager.levels  : 'مستويات',
  TranslationKeyManager.levelsA  : 'المستويات',
  TranslationKeyManager.editLevels  : 'تعديل المستويات',
  TranslationKeyManager.levelTitle  : 'اسم المستوي',
  TranslationKeyManager.remove  : 'حذف',
  TranslationKeyManager.edit  : 'تعديل',
  TranslationKeyManager.updateLocation  : 'تحديث الموقع',
  TranslationKeyManager.currentLocation  : 'الموقع الحالي',
  TranslationKeyManager.pickAnotherLocation  : 'اختيار موقع اخر',
  TranslationKeyManager.location  : 'الموقع',
  TranslationKeyManager.languages  : 'اللغات',
  TranslationKeyManager.students  : 'الطلاب',
  TranslationKeyManager.logout  : 'تسجيل خروج',
  TranslationKeyManager.yesLogout  : 'نعم, تسجيل خروج',
  TranslationKeyManager.noCancel  : 'لا, الغاء',
  TranslationKeyManager.sureUWantToLogout  : 'هل تريد تسجيل خروج؟',
  TranslationKeyManager.login  : 'تسجيل الدخول',
  TranslationKeyManager.email  : 'البريد الالكتروني',
  TranslationKeyManager.password  : 'كلمة المرور',
  TranslationKeyManager.passwordDoNotMatch  : 'كلمة المرور غير متطابقة',
  TranslationKeyManager.forgotPassword  : 'نسيت كلمة المرور؟',
  TranslationKeyManager.registerNow  : 'سجل الان',
  TranslationKeyManager.doNotHaveAnAccount  : 'ليس لديك حساب؟',
  TranslationKeyManager.chooseYUserType  : 'اختر نوع المستخدم',
  TranslationKeyManager.continueBTN  : 'التالي',
  TranslationKeyManager.newSchool  : 'انشاء حساب مدرسة',
  TranslationKeyManager.newParent  : 'انشاء حساب ولي امر',
  TranslationKeyManager.chooseImage  : 'اختر صورة',
  TranslationKeyManager.changeImage  : 'تغيير الصورة',
  TranslationKeyManager.name  : 'الاسم',
  TranslationKeyManager.phone  : 'الهاتف',
  TranslationKeyManager.address  : 'العنوان',
  TranslationKeyManager.confirmPassword  : 'تأكيد كلمة المرور',
  TranslationKeyManager.ssnRequired  : 'الرقم القومي مطلوب',
  TranslationKeyManager.ssn  : 'الرقم القومي',
  TranslationKeyManager.register  : 'تسجيل',
  TranslationKeyManager.assignKids  : 'اختيار الاطفال',
  TranslationKeyManager.kidName  : 'اسم الطفل',
  TranslationKeyManager.level  : 'المستوي',
  TranslationKeyManager.update  : 'تحديث',
  TranslationKeyManager.search  : 'بحث',
  TranslationKeyManager.searchForSchool  : 'ابحث عن مدرسة',
  TranslationKeyManager.kids  : 'الاطفال',
  TranslationKeyManager.kidsA  : 'اطفال',
  TranslationKeyManager.kid  : 'طفل',
  TranslationKeyManager.kidSchool  : 'مدرسة الطفل',
  TranslationKeyManager.kidSchools  : 'مدارس الطفل',
  TranslationKeyManager.nearBySchools  : 'المدارس القريبة',
  TranslationKeyManager.history  : 'السجل',
  TranslationKeyManager.joinRequest  : 'طلب انضمام',
  TranslationKeyManager.pickupRequestedSuccessfully : 'تم ارسال طلب الاستدعاء بنجاح',
  TranslationKeyManager.accountUpdatedSuccessfully : 'تم تحديث الحساب بنجاح',
  TranslationKeyManager.registerSuccessVerifyEmail : 'تم التسجيل بنجاح، يرجى التحقق من بريدك الالكتروني',
  TranslationKeyManager.editedSuccessfully : 'تم التعديل بنجاح',
  TranslationKeyManager.editSchoolLevel : 'تعديل المستوي',
  TranslationKeyManager.pleaseSelectNewLevel : 'الرجاء تحديد مستوي جديد',
  TranslationKeyManager.sureUWantToDelete : 'متأكد انك تريد الحذف؟',
  TranslationKeyManager.yesDelete : 'نعم, حذف',
  TranslationKeyManager.newSchoolLevel : 'مستوي جديد',
  TranslationKeyManager.add : 'اضافة',
  TranslationKeyManager.addSuccessfully : 'تمت الاضافة بنجاح',
  TranslationKeyManager.loading : 'جاري التحميل...',
  TranslationKeyManager.accept : 'قبول',
  TranslationKeyManager.reject : 'رفض',
  TranslationKeyManager.explainParentWhyReject : 'وضح الي ولي الامر سبب الرفض',
  TranslationKeyManager.reason : 'السبب',
  TranslationKeyManager.cancel : 'الغاء',
  TranslationKeyManager.plzChooseSchool : 'الرجاء تحديد المدرسة اولا',
  TranslationKeyManager.notEmpty : 'لا يجب ترك هذا الحقل فارغا',
  TranslationKeyManager.tooFar : 'المسافة بعيد عن المدرسة من فضلك اقترب اكثر',
  TranslationKeyManager.someThingWentWrong : 'حدث خطأ ما، حاول مرة اخرى',
  TranslationKeyManager.noSchoolFound : 'لم يتم العثور على المدرسة',
  TranslationKeyManager.waitForResponse : 'انتظر الرد',
  TranslationKeyManager.waitingForSchResForUKidReq : 'انتظر الرد من المدرسة لاستدعاء الطفل',
  TranslationKeyManager.schoolAcceptedUKidReq : 'المدرسة قبلت استدعاء الطفل',
  TranslationKeyManager.schoolRejectedUKidReq : 'المدرسة رفضت استدعاء الطفل',
  TranslationKeyManager.schoolReply : 'رد المدرسة',

};
