import 'package:call_son/core/localization/translation_key_manager.dart';

Map<String, String> en =
{
  TranslationKeyManager.home : 'Home',
  TranslationKeyManager.settings : 'Settings',
  TranslationKeyManager.hello : 'Hello',
  TranslationKeyManager.school : 'School',
  TranslationKeyManager.schoolA : 'School',
  TranslationKeyManager.schools: 'Schools',
  TranslationKeyManager.all: 'All',
  TranslationKeyManager.profile : 'Profile',
  TranslationKeyManager.pickup : 'Pickup',
  TranslationKeyManager.pickupRequests : 'Pickup Requests',
  TranslationKeyManager.waiting : 'Waiting',
  TranslationKeyManager.accepted  : 'Accepted',
  TranslationKeyManager.rejected  : 'Rejected',
  TranslationKeyManager.noData  : 'No Data',
  TranslationKeyManager.parents  : 'Parents',
  TranslationKeyManager.levels  : 'Levels',
  TranslationKeyManager.levelsA  : 'Levels',
  TranslationKeyManager.editLevels  : 'Edit Levels',
  TranslationKeyManager.levelTitle  : 'Level Title',
  TranslationKeyManager.remove  : 'Remove',
  TranslationKeyManager.edit  : 'Edit',
  TranslationKeyManager.updateLocation  : 'Update Location',
  TranslationKeyManager.currentLocation  : 'Current Location',
  TranslationKeyManager.pickAnotherLocation  : 'Pick Another Location',
  TranslationKeyManager.location  : 'Location',
  TranslationKeyManager.languages  : 'Languages',
  TranslationKeyManager.students  : 'Students',
  TranslationKeyManager.logout  : 'Logout',
  TranslationKeyManager.yesLogout  : 'Yes, Logout',
  TranslationKeyManager.noCancel  : 'No, Cancel',
  TranslationKeyManager.sureUWantToLogout  : 'Sure you want to logout?',
  TranslationKeyManager.login  : 'Login',
  TranslationKeyManager.email  : 'Email',
  TranslationKeyManager.password  : 'Password',
  TranslationKeyManager.passwordDoNotMatch  : 'Password Do Not Match',
  TranslationKeyManager.forgotPassword  : 'Forgot Password',
  TranslationKeyManager.registerNow  : 'Register Now',
  TranslationKeyManager.doNotHaveAnAccount  : 'Do\'t have an account?',
  TranslationKeyManager.chooseYUserType  : 'Choose Your User Type',
  TranslationKeyManager.continueBTN  : 'Continue',
  TranslationKeyManager.newSchool  : 'New School',
  TranslationKeyManager.newParent  : 'New Parent',
  TranslationKeyManager.chooseImage  : 'Choose Image',
  TranslationKeyManager.changeImage  : 'Change Image',
  TranslationKeyManager.name  : 'Name',
  TranslationKeyManager.phone  : 'Phone',
  TranslationKeyManager.address  : 'Address',
  TranslationKeyManager.confirmPassword  : 'Confirm Password',
  TranslationKeyManager.ssnRequired  : 'SSN Required',
  TranslationKeyManager.ssn  : 'SSN',
  TranslationKeyManager.register  : 'Register',
  TranslationKeyManager.assignKids  : 'Assign Kids',
  TranslationKeyManager.kidName  : 'Kid Name',
  TranslationKeyManager.level  : 'Level',
  TranslationKeyManager.update  : 'Update',
  TranslationKeyManager.search  : 'Search',
  TranslationKeyManager.searchForSchool  : 'Search For School',
  TranslationKeyManager.kids  : 'Kids',
  TranslationKeyManager.kidsA  : 'Kids',
  TranslationKeyManager.kid  : 'Kid',
  TranslationKeyManager.kidSchool  : 'Kid School',
  TranslationKeyManager.kidSchools  : 'Kid Schools',
  TranslationKeyManager.nearBySchools  : 'Near By Schools',
  TranslationKeyManager.history  : 'History',
  TranslationKeyManager.joinRequest  : 'Join Request',
  TranslationKeyManager.pickupRequestedSuccessfully : 'Pickup Requested Successfully',
  TranslationKeyManager.accountUpdatedSuccessfully : 'Account Updated Successfully',
  TranslationKeyManager.registerSuccessVerifyEmail : 'Register Success, Verify Email',
  TranslationKeyManager.editedSuccessfully : 'Edited Successfully',
  TranslationKeyManager.editSchoolLevel : 'Edit School Level',
  TranslationKeyManager.pleaseSelectNewLevel : 'Please Select New Level',
  TranslationKeyManager.sureUWantToDelete : 'Sure you want to delete?',
  TranslationKeyManager.yesDelete : 'Yes, Delete',
  TranslationKeyManager.newSchoolLevel : 'New School Level',
  TranslationKeyManager.add : 'Add',
  TranslationKeyManager.addSuccessfully : 'Add Successfully',
  TranslationKeyManager.loading : 'Loading...',
  TranslationKeyManager.accept : 'Accept',
  TranslationKeyManager.reject : 'Reject',
  TranslationKeyManager.explainParentWhyReject :  'Explain to the Parents, why you reject the call !',
  TranslationKeyManager.reason :  'Reason',
  TranslationKeyManager.cancel :  'Cancel',
  TranslationKeyManager.plzChooseSchool :  'Please Choose School First',
  TranslationKeyManager.notEmpty :  'This field cannot be empty',
  TranslationKeyManager.tooFar :  'the distance is too far please come closer',
  TranslationKeyManager.someThingWentWrong :  "Sorry, Something went wrong",


};
